
import type { Property, Builder, InteriorProject } from '@/types';

export const properties: Property[] = [
  {
    id: 'p1',
    userId: 'user1',
    title: 'Modern Apartment in South Delhi',
    propertyType: 'Apartment',
    location: 'South Delhi',
    price: 35000000, // 3.5 Cr
    bedrooms: 3,
    bathrooms: 3,
    squareFootage: 2200,
    listingType: 'sale',
    imageUrls: ['property-1'],
    description: 'A stunning modern apartment with breathtaking city views, premium fittings, and a spacious layout.',
    amenities: [],
    isFeatured: true,
    dateListed: new Date(),
  },
  {
    id: 'p2',
    userId: 'user2',
    title: 'Luxury Villa with Private Pool',
    propertyType: 'Villa',
    location: 'Chattarpur',
    price: 120000000, // 12 Cr
    bedrooms: 5,
    bathrooms: 6,
    squareFootage: 8000,
    listingType: 'sale',
    imageUrls: ['property-2'],
    description: 'An expansive villa offering ultimate privacy and luxury, complete with a private pool and landscaped gardens.',
    amenities: [],
    isFeatured: true,
    dateListed: new Date(),
  },
  {
    id: 'p3',
    userId: 'user1',
    title: 'Sky-High Penthouse',
    propertyType: 'Penthouse',
    location: 'Central Delhi',
    price: 87500000, // 8.75 Cr
    bedrooms: 4,
    bathrooms: 5,
    squareFootage: 4500,
    listingType: 'sale',
    imageUrls: ['property-3'],
    description: 'Experience life at the top in this exquisite penthouse with panoramic views and world-class amenities.',
    amenities: [],
    isFeatured: true,
    dateListed: new Date(),
  },
  {
    id: 'p4',
    userId: 'user3',
    title: 'Serene Farmhouse Getaway',
    propertyType: 'Farmhouse',
    location: 'Mehrauli',
    price: 155000000, // 15.5 Cr
    bedrooms: 6,
    bathrooms: 7,
    squareFootage: 15000,
    listingType: 'sale',
    imageUrls: ['property-4'],
    description: 'A peaceful retreat from the city, this farmhouse boasts lush greenery, modern comforts, and ample space.',
    amenities: [],
    isFeatured: false,
    dateListed: new Date(),
  },
  {
    id: 'p5',
    userId: 'user2',
    title: 'Chic Hauz Khas Apartment',
    propertyType: 'Apartment',
    location: 'Hauz Khas',
    price: 21000000, // 2.1 Cr
    bedrooms: 2,
    bathrooms: 2,
    squareFootage: 1500,
    listingType: 'rent',
    imageUrls: ['property-5'],
    description: 'A stylish apartment in the trendy Hauz Khas area, perfect for young professionals and artists.',
    amenities: [],
    isFeatured: false,
    dateListed: new Date(),
  },
  {
    id: 'p6',
    userId: 'user3',
    title: 'Gurgaon Corporate Penthouse',
    propertyType: 'Penthouse',
    location: 'Gurgaon',
    price: 92000000, // 9.2 Cr
    bedrooms: 4,
    bathrooms: 4,
    squareFootage: 4800,
    listingType: 'sale',
    imageUrls: ['property-6'],
    description: 'Located in the heart of Gurgaon, this penthouse is ideal for corporate leaders, offering luxury and convenience.',
    amenities: [],
    isFeatured: true,
    dateListed: new Date(),
  },
  {
    id: 'p7',
    userId: 'user1',
    title: 'Independent House in Vasant Kunj',
    propertyType: 'House',
    location: 'Vasant Kunj',
    price: 65000000, // 6.5 Cr
    bedrooms: 4,
    bathrooms: 4,
    squareFootage: 3500,
    listingType: 'sale',
    imageUrls: ['property-1'],
    description: 'A beautiful independent house in a quiet and green lane of Vasant Kunj, close to malls and the airport.',
    amenities: [],
    isFeatured: false,
    dateListed: new Date(),
  },
  {
    id: 'p8',
    userId: 'user2',
    title: '2BHK for Rent in Noida',
    propertyType: 'Apartment',
    location: 'Noida',
    price: 35000, // 35k rent
    bedrooms: 2,
    bathrooms: 2,
    squareFootage: 1200,
    listingType: 'rent',
    imageUrls: ['property-5'],
    description: 'A spacious and modern 2BHK apartment available for rent in a prime location in Noida, with all amenities.',
    amenities: [],
    isFeatured: false,
    dateListed: new Date(),
  },
  {
    id: 'p9',
    userId: 'user3',
    title: 'Plot for Sale in Greater Noida',
    propertyType: 'Plot',
    location: 'Greater Noida',
    price: 12000000, // 1.2 Cr
    bedrooms: 0,
    bathrooms: 0,
    squareFootage: 2150,
    listingType: 'sale',
    imageUrls: ['property-4'],
    description: 'A 200 sq. meter plot in a gated community in Greater Noida, perfect for building your dream home.',
    amenities: [],
    isFeatured: false,
    dateListed: new Date(),
  },
   {
    id: 'p10',
    userId: 'user1',
    title: 'Modern PG in Mukherjee Nagar',
    propertyType: 'PG',
    location: 'Mukherjee Nagar',
    price: 15000,
    bedrooms: 1,
    bathrooms: 1,
    squareFootage: 250,
    listingType: 'rent',
    imageUrls: ['property-5'],
    description: 'Fully furnished single room PG with AC, Wi-Fi, and meals included. Perfect for students.',
    amenities: ['AC', 'Wi-Fi', 'Meals'],
    isFeatured: false,
    dateListed: new Date(),
  },
  {
    id: 'p11',
    userId: 'user2',
    title: 'Spacious 4BHK in Dwarka',
    propertyType: 'Apartment',
    location: 'Dwarka',
    price: 28000000, // 2.8 Cr
    bedrooms: 4,
    bathrooms: 4,
    squareFootage: 2500,
    listingType: 'sale',
    imageUrls: ['property-1'],
    description: 'A large and airy 4BHK apartment in a well-connected sector of Dwarka, with park views.',
    amenities: ['Gated Community', 'Park'],
    isFeatured: false,
    dateListed: new Date(),
  },
  {
    id: 'p12',
    userId: 'user3',
    title: 'Office Space for Rent in Connaught Place',
    propertyType: 'Commercial',
    location: 'Connaught Place',
    price: 250000, // 2.5 Lakh rent
    bedrooms: 0,
    bathrooms: 2,
    squareFootage: 2000,
    listingType: 'rent',
    imageUrls: ['property-6'],
    description: 'Prime office space in the heart of Delhi. Fully furnished and ready to move in for your business.',
    amenities: ['Central AC', 'Power Backup'],
    isFeatured: true,
    dateListed: new Date(),
  },
];

export const builders: Builder[] = [
  {
    id: 'b1',
    name: 'DLF',
    logo: 'builder-logo-2',
    description: 'With over 70 years of experience, DLF is a name synonymous with quality and trust in Indian real estate.',
  },
  {
    id: 'b2',
    name: 'Godrej Properties',
    logo: 'builder-logo-3',
    description: 'Bringing the Godrej Group philosophy of innovation, sustainability, and excellence to the real estate industry.',
  },
  {
    id: 'b3',
    name: 'Emaar India',
    logo: 'builder-logo-1',
    description: 'One of the leading real estate developers in the country, with a legacy of creating iconic projects.',
  },
  {
    id: 'b4',
    name: 'Omaxe',
    logo: 'builder-logo-4',
    description: 'Known for their passion for perfection, Sobha developers are committed to delivering the highest quality.',
  },
  {
    id: 'b5',
    name: 'Ansal API',
    logo: 'builder-logo-5',
    description: 'A pioneer in creating green buildings and sustainable living spaces across India.',
  },
];

export const interiorProjects: InteriorProject[] = [
  {
    id: 'i1',
    title: 'The Minimalist Haven',
    description: 'A project focused on clean lines, neutral palettes, and creating a sense of calm and space. This design philosophy embraces simplicity to create a serene and uncluttered environment.',
    images: ['interior-1-1', 'interior-1-2', 'interior-1-3'],
  },
  {
    id: 'i2',
    title: 'Classic Elegance Redefined',
    description: 'This project blends timeless design elements with modern luxury. Featuring ornate details, rich textures, and a sophisticated color scheme, it evokes a sense of grandeur and classic style.',
    images: ['interior-2-1', 'interior-2-2', 'interior-2-3'],
  },
  {
    id: 'i3',
    title: 'Urban Modern Loft',
    description: 'Exposed brick, metal accents, and an open-concept layout define this edgy, urban space. It combines industrial elements with modern comforts for a unique city living experience.',
    images: ['interior-3-1', 'interior-3-2', 'interior-3-3'],
  },
  {
    id: 'i4',
    title: 'Bohemian Chic Retreat',
    description: 'A vibrant and eclectic mix of patterns, textures, and natural elements. This style is for the free-spirited, creating a warm, inviting, and personalized atmosphere.',
    images: ['interior-4-1', 'interior-4-2', 'interior-4-3'],
  },
  {
    id: 'i5',
    title: 'Scandinavian Sanctuary',
    description: 'Light-filled and functional, this design emphasizes simplicity, minimalism, and a connection to nature. Light wood tones and cozy textiles create a hygge-inspired living space.',
    images: ['interior-5-1', 'interior-5-2', 'interior-5-3'],
  },
  {
    id: 'i6',
    title: 'Industrial Edge',
    description: 'Raw materials like concrete and steel meet refined finishes. High ceilings and large windows create a dramatic and spacious feel, perfect for a contemporary lifestyle.',
    images: ['interior-6-1', 'interior-6-2', 'interior-6-3'],
  },
];
